# Generated by Django 6.0.4 on 2026-04-17 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('business_type', models.CharField(blank=True, choices=[('ecommerce', 'E-commerce'), ('saas', 'SaaS'), ('agency', 'Agency'), ('content_creator', 'Content Creator'), ('local_business', 'Local Business'), ('other', 'Other')], max_length=30)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('primary_goal', models.CharField(blank=True, choices=[('product_ads', 'Product Ads'), ('social_content', 'Social Content'), ('brand_awareness', 'Brand Awareness'), ('tutorials', 'Tutorials'), ('testimonials', 'Testimonials'), ('promotions', 'Promotions')], max_length=30)),
                ('target_platforms', models.JSONField(blank=True, default=list)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('credits', models.IntegerField(default=10)),
                ('monthly_credits', models.IntegerField(default=200)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('agency', 'Agency')], default='free', max_length=10)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
